import { colors, fonts, radii } from '../../theme';

export const homeStyles = () => ({
  pageWrapper: {
    backgroundColor: colors.background,
    minHeight: '100vh',
    overflowX: 'hidden' as const,
  },
  container: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    px: { xs: 3, md: 6 },
  },

  // Hero
  hero: {
    width: '100%',
    minHeight: { xs: '70vh', md: '85vh' },
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    textAlign: 'center',
    pt: { xs: 16, md: 18 },
    pb: { xs: 8, md: 10 },
  },
  heroTitle: {
    fontFamily: fonts.heading,
    fontWeight: 700,
    fontSize: { xs: '2.6rem', sm: '3.5rem', md: '4.5rem' },
    color: colors.textPrimary,
    letterSpacing: '0.02em',
  },
  heroSubtitle: {
    fontFamily: fonts.heading,
    fontSize: { xs: '1.2rem', md: '1.75rem' },
    color: colors.textPrimary,
    mt: 1,
  },
  heroTagline: {
    fontFamily: fonts.heading,
    fontSize: { xs: '0.85rem', md: '1rem' },
    color: colors.textSecondary,
    mt: 4,
    px: 2,
  },
  heroButtons: {
    display: 'flex',
    gap: 2,
    mt: 5,
    flexWrap: 'wrap',
    justifyContent: 'center',
  },
  primaryButton: {
    fontFamily: fonts.body,
    fontSize: '0.95rem',
    fontWeight: 500,
    textTransform: 'none',
    color: colors.textPrimary,
    backgroundColor: colors.purpleButton,
    borderRadius: '8px',
    px: 3,
    py: 1.2,
    '&:hover': { backgroundColor: colors.purpleBright },
  },
  secondaryButton: {
    fontFamily: fonts.body,
    fontSize: '0.95rem',
    fontWeight: 500,
    textTransform: 'none',
    color: colors.textPrimary,
    border: `1px solid ${colors.purple}`,
    borderRadius: '8px',
    px: 3,
    py: 1.2,
    '&:hover': { borderColor: colors.purpleBright, backgroundColor: 'rgba(114, 93, 240, 0.1)' },
  },

  // Shared section pieces
  sectionWrapper: {
    width: '100%',
    maxWidth: '1100px',
    py: { xs: 6, md: 9 },
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
  },
  sectionTitle: {
    fontFamily: fonts.heading,
    fontWeight: 700,
    fontSize: { xs: '1.8rem', md: '2.4rem' },
    color: colors.textPrimary,
    textAlign: 'center',
  },
  sectionSubtitle: {
    fontFamily: fonts.heading,
    fontSize: { xs: '0.85rem', md: '0.95rem' },
    color: colors.textSecondary,
    textAlign: 'center',
    mt: 1.5,
  },

  // What is CSES?
  aboutParagraph: {
    fontFamily: fonts.heading,
    fontSize: { xs: '0.85rem', md: '1rem' },
    lineHeight: 1.9,
    color: colors.textSecondary,
    textAlign: 'center',
    maxWidth: '850px',
    mt: 4,
  },

  // Communities
  communityColumn: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    textDecoration: 'none',
    cursor: 'pointer',
    transition: 'transform 0.2s ease',
    '&:hover': { transform: 'translateY(-4px)' },
  },
  communityLogo: {
    width: '100%',
    maxWidth: '220px',
    height: 'auto',
  },
  communityCard: (accent: string) => ({
    backgroundColor: colors.surface,
    border: `1px solid ${accent}55`,
    borderRadius: radii.card,
    p: 3,
    mt: 3,
    width: '100%',
    minHeight: '96px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  }),
  communityCardText: {
    fontFamily: fonts.body,
    fontSize: '0.95rem',
    color: colors.textSecondary,
    textAlign: 'center',
  },

  // Meet the Team!
  teamTabsWrapper: {
    width: '100%',
    maxWidth: '800px',
    mt: 5,
  },
  teamGrid: {
    mt: 4,
    width: '100%',
  },
  teamCard: {
    backgroundColor: colors.surface,
    border: `1px solid ${colors.border}`,
    borderRadius: radii.card,
    p: 2.5,
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    textAlign: 'center',
    height: '100%',
  },
  teamPhoto: {
    width: '96px',
    height: '96px',
    borderRadius: '50%',
    objectFit: 'cover' as const,
  },
  teamName: {
    fontFamily: fonts.body,
    fontWeight: 600,
    fontSize: '1rem',
    color: colors.textPrimary,
    mt: 2,
  },
  teamRole: {
    fontFamily: fonts.body,
    fontSize: '0.85rem',
    color: colors.textSecondary,
    mt: 0.5,
  },
  dotsWrapper: {
    display: 'flex',
    gap: 1.2,
    mt: 4,
  },
  dot: {
    width: '10px',
    height: '10px',
    borderRadius: '50%',
    backgroundColor: 'rgba(255, 255, 255, 0.25)',
    cursor: 'pointer',
  },
  dotActive: {
    width: '10px',
    height: '10px',
    borderRadius: '50%',
    backgroundColor: colors.purpleBright,
    cursor: 'pointer',
  },
  emptyText: {
    fontFamily: fonts.body,
    color: colors.textSecondary,
    mt: 4,
  },

  // Kept for consumers outside Home (e.g. About/HowToJoin).
  ctaButton: {
    fontFamily: fonts.body,
    fontSize: '0.95rem',
    fontWeight: 500,
    textTransform: 'none',
    color: colors.textPrimary,
    border: `1px solid ${colors.purple}`,
    borderRadius: '8px',
    px: 3,
    py: 1.2,
    '&:hover': { borderColor: colors.purpleBright, backgroundColor: 'rgba(114, 93, 240, 0.1)' },
  },
});
